MOVIEPROJECT/MOVIEPROJECT/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from MOVIEPROJECT import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MOVIEPROJECT/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')


]

MOVIEPROJECT/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    objects = None
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

MOVIEPROJECT/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

MOVIEPROJECT/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import MovieForm
from . models import Movie

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    # return HttpResponse("Hello,Welcome to MOVIE PROJECT",context)
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    # return HttpResponse("This is Movie No. %s" % movie_id)
    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc, year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

MOVIEPROJECT/templates/add.html
{% extends 'base.html' %}
{% block body %}
<br><br>
<body style="background-color:pink;">
<h2 style="background-color:grey;color:white;font-size:200%;text-align:center;">Add your Favourite Movie</h2><br><br>
<div align="center" style="white">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <input type="text" name="name" placeholder="Movie Name"><br>
            <input type="text" name="desc" placeholder="Description"><br>
            <input type="text" name="year" placeholder="Release Year"><br>
            <input type="file" name="img"><br><br>
            <input type="submit">
    </form>
</div>
</body>
{% endblock %}








</form>

MOVIEPROJECT/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#" >
      <h2 style="font-size:200%;color:red;">Online Movie Store</h2>
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

MOVIEPROJECT/templates/delete.html
<body style="background-color:pink;">
<br><br><br><br>
<div align="center" style="white">

    <form method="POST">

        {% csrf_token %}
        <h2 style="background-color:grey;color:white;font-size:200%;">Do you want to delete this Movie?</h2><br><br>
        <input type="submit">
    </form>

</div>
</body>

MOVIEPROJECT/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            <h6>{{movie.year}}</h6>
            <a class="btn btn-warning" href = "{% url 'movieapp:update' movie.id %}">EDIT</a>
            <a class="btn btn-danger" href = "{% url 'movieapp:delete' movie.id %}">DELETE</a>
        </div>
    </div>
</div>

{% endblock %}

MOVIEPROJECT/templates/edit.html
<body style="background-color:pink;">
<br><br><br>

<form method="POST" enctype="multipart/form-data">

      {% csrf_token %}
      {{form.as_p}}
      <input type="submit">

</form>
</body>

MOVIEPROJECT/templates/index.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#" ></a>
    <div align="right" >
        <a class="btn btn-warning" href = "{% url 'movieapp:add_movie' %}">ADD MOVIE</a>
    </div>
</nav>
<br><br>
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{i.img.url}}" class="card-img-top" alt="..." width="180" height="250">
                <div class="card-body">
                    <h6 class="card-title"><b>{{i.name}}</b></h6>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">More Details...</a>
                </div>
            </div>
            <br><br>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}